### ISSUE TITLE
GitBook question

### ISSUE THREAD

**Issue by nenniuwufang** [waylau/harmonyos-tutorial#1]
大佬 那个gitbook的链接好像挂了 显示的是404无法找到该书籍

**Comment by waylau** [comment]
@nenniuwufang 
嗯，暂时还没有时间弄 gitbook。直接选择下面入口之一开始阅读：

https://github.com/waylau/harmonyos-tutorial 的 README.md
https://gitee.com/waylau/harmonyos-tutorial 的 README.md

**Comment by nenniuwufang** [comment]
> @nenniuwufang
> 嗯，暂时还没有时间弄 gitbook。直接选择下面入口之一开始阅读：
> 
> https://github.com/waylau/harmonyos-tutorial 的 README.md
> https://gitee.com/waylau/harmonyos-tutorial 的 README.md

好的 谢谢大佬~
