### ISSUE TITLE
请问是否有关于IDL的相关demo？

### ISSUE THREAD

**Issue by kingrukawa** [waylau/harmonyos-tutorial#22]
我在测试Harmoney的IDL进程通信是发现，鸿蒙的ipc性能还不如android的原生binder性能，让我大跌眼镜，我的测试结果放到了：https://developer.huawei.com/consumer/cn/forum/topic/0204724606002160521?fid=0101591351254000314
请问一下老魏，是否可以指点一二

**Comment by waylau** [comment]
@kingrukawa   没有这方面的研究。如果是鸿蒙套AOSP的API话，性能比原生的API差应该也是能解释的。
